server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml 
  
spring:
  application:
    name: msa-service-coffee-member

#Config Server      
  cloud:
    config:
      uri: http://172.20.10.2:8888 
      name: msa-architecture-config-server

#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.20.10.2:9091/eureka/
      
